=== photonsquid/Recoinize-scraper/src/schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "url": {
                "type": "string",
                "format": "uri"
            },
            "particularity": {
                "type": [
                    "string",
                    "null"
                ]
            },
            "countryCode": {
                "type": "string"
            },
            "value": {
                "type": "string"
            },
            "countryName": {
                "type": "string"
            },
            "imageExtension": {
                "type": "string"
            },
            "specialPath": {
                "type": [
                    "string",
                    "null"
                ]
            }
        },
        "required": [
            "url",
            "particularity",
            "countryCode",
            "value",
            "countryName",
            "imageExtension",
            "specialPath"
        ]
    }
}

=== photonsquid/Recoinize-scraper/out/ECB.json
[
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/ad/ad_2euro.jpg",
        "particularity": null,
        "countryCode": "ad",
        "imageExtension": "jpg",
        "countryName": "Andorra",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/at/Austria_2Euro.jpg",
        "particularity": null,
        "countryCode": "at",
        "imageExtension": "jpg",
        "countryName": "Austria",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_2euroAl.jpg",
        "particularity": "2euroAl",
        "countryCode": "be",
        "imageExtension": "jpg",
        "countryName": "Belgium",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_2euro_2008.jpg",
        "particularity": "2008",
        "countryCode": "be",
        "imageExtension": "jpg",
        "countryName": "Belgium",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/be/Belgium_2euro_2014ph.jpg",
        "particularity": "2014ph",
        "countryCode": "be",
        "imageExtension": "jpg",
        "countryName": "Belgium",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/hr/Croatia_2euro.jpg",
        "particularity": null,
        "countryCode": "hr",
        "imageExtension": "jpg",
        "countryName": "Croatia",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/cy/Cyprus_2Euro.jpg",
        "particularity": null,
        "countryCode": "cy",
        "imageExtension": "jpg",
        "countryName": "Cyprus",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/et/Estonia_2Euro.jpg",
        "particularity": null,
        "countryCode": "et",
        "imageExtension": "jpg",
        "countryName": "Estonia",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/fi/Finland_2euro.jpg",
        "particularity": null,
        "countryCode": "fi",
        "imageExtension": "jpg",
        "countryName": "Finland",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_2euro.jpg",
        "particularity": "2euro",
        "countryCode": "fr",
        "imageExtension": "jpg",
        "countryName": "France",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/fr/France_2euro_2022.jpg",
        "particularity": "2022",
        "countryCode": "fr",
        "imageExtension": "jpg",
        "countryName": "France",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/de/Germany_2euro.jpg",
        "particularity": null,
        "countryCode": "de",
        "imageExtension": "jpg",
        "countryName": "Germany",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/gr/Greece_2euro.jpg",
        "particularity": null,
        "countryCode": "gr",
        "imageExtension": "jpg",
        "countryName": "Greece",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/ie/Ireland_2euro.jpg",
        "particularity": null,
        "countryCode": "ie",
        "imageExtension": "jpg",
        "countryName": "Ireland",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/it/Italy_2euro.jpg",
        "particularity": null,
        "countryCode": "it",
        "imageExtension": "jpg",
        "countryName": "Italy",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/lv/Latvia_2euro.jpg",
        "particularity": null,
        "countryCode": "lv",
        "imageExtension": "jpg",
        "countryName": "Latvia",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/lt/Lithuania_2euro_2015.jpg",
        "particularity": null,
        "countryCode": "lt",
        "imageExtension": "jpg",
        "countryName": "Lithuania",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/lu/Luxembourg_2euro.jpg",
        "particularity": null,
        "countryCode": "lu",
        "imageExtension": "jpg",
        "countryName": "Luxembourg",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/mt/Malta_2euro.jpg",
        "particularity": null,
        "countryCode": "mt",
        "imageExtension": "jpg",
        "countryName": "Malta",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/2e.jpg",
        "particularity": "2e",
        "countryCode": "mo",
        "imageExtension": "jpg",
        "countryName": "Monaco",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/mo/Monaco_2euro.jpg",
        "particularity": "2euro",
        "countryCode": "mo",
        "imageExtension": "jpg",
        "countryName": "Monaco",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_2euro_2001.jpg",
        "particularity": "2001",
        "countryCode": "nl",
        "imageExtension": "jpg",
        "countryName": "Netherlands",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/nl/Netherlands_2Euro.jpg",
        "particularity": "2Euro",
        "countryCode": "nl",
        "imageExtension": "jpg",
        "countryName": "Netherlands",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/pt/Portugal_2euro.jpg",
        "particularity": null,
        "countryCode": "pt",
        "imageExtension": "jpg",
        "countryName": "Portugal",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_2euro_2010.jpg",
        "particularity": "2010",
        "countryCode": "sm",
        "imageExtension": "jpg",
        "countryName": "San Marino",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/sm/SanMarino_2euro_2017.jpg",
        "particularity": "2017",
        "countryCode": "sm",
        "imageExtension": "jpg",
        "countryName": "San Marino",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/sk/Slovakia_2Euro.jpg",
        "particularity": null,
        "countryCode": "sk",
        "imageExtension": "jpg",
        "countryName": "Slovakia",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/sl/Slovenia_2Euro.jpg",
        "particularity": null,
        "countryCode": "sl",
        "imageExtension": "jpg",
        "countryName": "Slovenia",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_2Euro_2003.jpg",
        "particularity": "2003",
        "countryCode": "es",
        "imageExtension": "jpg",
        "countryName": "Spain",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_2euro_2014.jpg",
        "particularity": "2014",
        "countryCode": "es",
        "imageExtension": "jpg",
        "countryName": "Spain",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/es/Spain_2euro_2015.jpg",
        "particularity": "2015",
        "countryCode": "es",
        "imageExtension": "jpg",
        "countryName": "Spain",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vaticano_2euro_2002.jpg",
        "particularity": "2002",
        "countryCode": "va",
        "imageExtension": "jpg",
        "countryName": "Vatican City",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vaticano_2euro_SedeVacante.jpg",
        "particularity": "SedeVacante",
        "countryCode": "va",
        "imageExtension": "jpg",
        "countryName": "Vatican City",
        "value": "2euro",
        "specialPath": null
    },
    {
        "url": "https://www.ecb.europa.eu/euro/coins/common/shared/img/va/Vaticano_2euro_2013.jpg",
        "particularity": "2013",
        "countryCode": "va",
        "imageExtension": "jpg",
        "countryName": "Vatican City",
        "value": "2euro",
        "specialPath": null
    },
    {
